### ISSUE TITLE
Simplify use with callback-style tests

### ISSUE THREAD

**Issue by PandaWhisperer** [dashkite/amen#2]
Let's say I have a test that requires using callbacks. Yes, it's terrible, but sometimes unavoidable. Not because of the test candidate, but some other module I might be using, for instance, [supertest](https://github.com/visionmedia/supertest), which has a fluent (jQuery-style) API that [ends with a callback-accepting function](https://github.com/visionmedia/supertest#endfn).

A test might look like this (apologies for plain JS):

``` javascript
request(app)
  .get('/user')
  .expect(200)
  .end(function(err, res){
    if (err) throw err;
  });
```

It would be nice if I could just grab a `done` function from the test's arguments and pass it to `end`. 

The best workaround I've currently come up with:

``` coffeescript
{promise} = require "when"

context.test "Request", ->
  yield promise (resolve, reject) ->
    done = (err, result) ->
      reject err if err?
      resolve result

    request(app)
       .get('/user')
      .expect(200)
      .end(done)
```

Since that custom `done` function knows nothing about my test, it can be re-used:

``` coffeescript
{promise} = require "when"

attempt = (fn) ->
  promise (resolve, reject) ->
    done = (err, result) ->
      reject err if err?
      resolve result
    fn done

context.test "Test", ->
  yield attempt (done) ->
    request(app)
       .get('/user')
      .expect(200)
      .end(done)
```

Is there perhaps a more convenient way to do this? I searched the when API for something like the `attempt` function but came up empty handed. Of course, if this could be built into amen without much complication, it would be even sleeker.

**Comment by dyoder** [comment]
just do this:

``` coffee
context. test "test", (context) ->
  asyncFnTakingCB (error, result) ->
    if error? then context.fail error else context.pass()
```

**Comment by PandaWhisperer** [comment]
Would it make sense to define `pass` and `fail` with fat arrows, so we could write this as

``` coffeescript
context. test "test", ({pass, fail}) ->
  asyncFnTakingCB (error, result) ->
    if error? then fail error else pass()
```

?

**Comment by dyoder** [comment]
Possibly. It's sort of an edge case for Amen, but I'm not opposed to it.

**Comment by PandaWhisperer** [comment]
Just to add the conclusion we came to on IRC: for callbacks, [Testify](https://github.com/automatthew/testify) is the better choice. Amen is optimized for ES6 promises and generators.
